build-aux/com.github.nahuelwexd.UniTube.json, data/ui/main-header-bar.ui, data/ui/main-window.ui, data/ui/preferences-window.ui, data/ui/trending-view.ui, src/app.vala, src/meson.build, src/widgets/main-header-bar.vala, src/windows/main-window.vala
Libhandy 1.0 will land sometime before I finish the development of this app, so I need to be prepared for that.
This PR contains everything needed to have a working app with the new features of Libhandy
=> Migrate to libhandy-1

src/widgets/replay-carousel.vala, src/widgets/replay-header-bar.vala, src/widgets/replay-navigation-view.vala, src/widgets/replay-video-carousel-item.vala
=> General: Use the new `with` keyword when possible

.github/workflows/CI.yml, CONTRIBUTING.md
Added a set of guidelines for contributing in this project
=> General: Added contributing guidelines

build-aux/flatpak/com.github.nahuelwexd.Replay.json, build-aux/flatpak/com.github.nahuelwexd.Replay.yml
This was only a problem in Builder, given the way it created the sandbox
=> Flatpak: Fixed CRITICALs flooding the output on Builder

build-aux/flatpak/com.github.nahuelwexd.Replay.json, build-aux/flatpak/com.github.nahuelwexd.Replay.yml, meson.build, src/Application.vala, src/ApplicationWindow.ui, src/ApplicationWindow.vala, src/Pages/HomePage.ui, src/Widgets/HeaderBar.ui, src/Widgets/HeaderBar.vala, src/meson.build, subprojects/libadwaita.wrap, subprojects/libhandy.wrap
=> Migrate to libadwaita

src/application-window.ui, src/application-window.vala, src/application.vala, src/widgets/header-bar.ui, src/widgets/header-bar.vala, src/widgets/stack-sidebar.vala, src/widgets/video-carousel-item.vala
Lots of code cleanup and improved comments for easier-to-understand code
Depends on #63
=> general: cleanups and improved comments

CONTRIBUTING.md
Updated contributing guidelines regarding what is indicated in issue #62
Fixes #62
=> contributing guidelines: updated with latest changes

src/meson.build, src/views/view.vala
See https://github.com/nahuelwexd/Replay/issues/64
=> Views: Added view base class

build-aux/flatpak/com.github.replaydev.Replay.json
For more info, see https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/251
=> tools: add support for libadwaita page in GtkInspector

.editorconfig, CONTRIBUTING.md, src/application-window.vala, src/application.vala, src/views/view.vala
- Lowered visibility of everything
- Removed all unnecessary keywords
- Reduced number of lines where possible
- Updated the contributing guidelines
=> Update code style

src/app-window.ui, src/app-window.vala, src/app.vala, src/application-window.vala, src/application.vala, src/meson.build, src/replay-ui-resources.xml, src/views/view.vala, vapi/config.vapi
A set of changes I wanted to make a long time ago but it wasn't worth putting in separate PRs.
=> Several changes and refactorings

src/app.vala, src/replay-ui-resources.xml
At the time of submitting #112, I missed 2 commits. Here they are
=> Several changes and refactorings pt 2

build-aux/flatpak/com.github.replaydev.Replay.json
flatpak-builder should be able to do the right thing
=> manifest: use the modules property instead of ordering manually

build-aux/flatpak/com.github.replaydev.Replay.json
=> Revert "manifest: use the modules property instead of ordering manually"

src/Features/Trends/TrendsView.ui, src/Widgets/Navigator.vala, src/Widgets/View.css, src/Widgets/View.vala
Replace AdwLeaflet with AdwNavigationView, and make RpyView a subclass of AdwNavigationPage. Switch to using the new named colors.
=> general: migrate to libadwaita 1.4

src/Repositories/VideoRepository.vala
yt.funami.tech stopped working
=> repository: hardcode new instance

src/Features/Trends/TrendsView.blp, src/Features/Trends/VideoItem.blp, src/Features/Trends/VideoItem.vala, src/Models/Video.vala, src/style.css
Video cards now have a badge indicating their duration
=> video-item: add duration badge

src/Errors/meson.build, src/Repositories/VideoRepository.vala, src/meson.build, subprojects/invidious-api/meson.build, subprojects/invidious-api/src/Client.vala, subprojects/invidious-api/src/Shared/Error.vala, subprojects/invidious-api/src/Shared/Request.vala, subprojects/invidious-api/src/Shared/Utils/EnumAsString.vala, subprojects/invidious-api/src/Shared/Utils/UriBuilder.vala, subprojects/invidious-api/src/Shared/Utils/meson.build, subprojects/invidious-api/src/Shared/meson.build, subprojects/invidious-api/src/Trending/TrendingRequest.vala, subprojects/invidious-api/src/Trending/Video.vala, subprojects/invidious-api/src/Trending/meson.build, subprojects/invidious-api/src/meson.build
In order to reduce the amount of knowledge the app has about Invidious, this pull request moves all the code related to Invidious requests to a new library. I also took the liberty of restructuring everything in a way that makes integrating new requests easier, as well as providing a simple to use API.
=> general: introduce invidious-api library

.github/actions/build-replay/action.yml
Added missing `shell` property
=> ci: fix build-replay action

.github/actions/build-replay/action.yml, .github/workflows/build-artifacts.yml, .github/workflows/publish-release.yml
=> ci: some refactorings and improvements
